name: Auto-merge -> Master-branch.

on:
  push:
    branches: 
      develop

jobs:
  automerge:
    if: startsWith( github.event.head_commit.message , 'automerge:')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create PR
      uses: technote-space/create-pr-action@v2
      with:
        COMMIT_MESSAGE: 'automerge: merge develop to master.'
        COMMIT_NAME: 'GitHub Actions'
        PR_BRANCH_NAME: 'automerge'
        PR_TITLE: 'Auto-PR-${PR_ID}'
       
    - name: Tag PR
      uses: TimonVS/pr-labeler-action@v3
      with:
        configuration-path: .github/labels.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
    - name: Merge PR
      uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
