name: AutoMerge

on:
  push:
    branches:
      - develop

jobs:  
  automerge:
    name: "AutoMerge™"
    if:  startsWith(github.event.head_commit.message, 'AutoMerge:')
    runs-on: "ubuntu-latest"
    steps:
      - name: "Create AutoMerge™ PR"
        uses: "actions/github-script@v2"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const repository = context.repo
            await github.pulls.create({
              owner: repository.owner,
              repo: repository.repo,
              title: "AutoMerge™",
              head: "develop",
              base: "master",
              body: "Automatically merged through AutoMerge™ by Github Actions. :rocket:"
            })
            
      - name: "Find PR"
        uses: juliangruber/find-pull-request-action@v1
        id: find-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop

      - name: "Merge AutoMerge™ PR"
        uses: "actions/github-script@v2"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const repository = context.repo
            await github.pulls.merge({
              merge_method: "merge",
              owner: repository.owner,
              pull_number: ${{ steps.find-pr.outputs.number }},
              repo: repository.repo,
            })
