name: Deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Build
        run: |
          yarn install --frozen-lockfile 
          yarn build

      #     - name: Upload Artifact
      #       uses: actions/upload-artifact@v2
      #       with:
      #         path: build

      - name: List Build
        run: |
          ls dist

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          port: 21
          server: ${{ secrets.FTP }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PW }}
          local-dir: dist/
          server-dir: albertsm.it/wwwroot/
