name: Deploy

on:
  push:
    branches: 
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2.1.0

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Build
      run: |
        npm ci
        npm run build
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: build

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PW }}
        local-dir: build
